# Generated by Django 3.0.6 on 2020-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200608_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myresume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
