# Generated by Django 3.0.6 on 2020-06-09 20:18

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_myresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='myresume',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myresume',
            name='resume',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
